version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: 3d-studio-server
    ports:
      - '5000:5000'
    env_file:
      - ./server/.env
    environment:
      - CLIENT_URL=http://localhost
    volumes:
      - server_uploads:/app/uploads

  # The React App
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: 3d-studio-client
    ports:
      - '80:3000'
    depends_on:
      - server

volumes:

  server_uploads:
